defmodule Pincer.Core do
  @moduledoc "The Absolute Domain Core of Pincer."
  use Boundary,
    deps: [Pincer.Ports, Pincer.Infra, Pincer.Utils],
    exports: [
      Session.Server,
      Session.Supervisor,
      Project.Server,
      Project.Supervisor,
      ProjectRouter,
      ProjectOrchestrator,
      Structs.IncomingMessage,
      Executor,
      UX,
      UX.MenuPolicy,
      UX.ModelKeyboard,
      Cron,
      Pairing,
      Bindings,
      AgentRegistry,
      AccessPolicy,
      SessionScopePolicy,
      SessionResolver,
      Session.Context,
      MemoryTypes,
      MemoryDiagnostics,
      MemoryObservability,
      ChannelInteractionPolicy,
      StreamingPolicy,
      StreamDelivery,
      ResponseEnvelope,
      StatusMessagePolicy,
      StatusDelivery,
      RetryPolicy,
      Telemetry,
      AuthProfiles,
      Models.Registry,
      LLM.FailoverPolicy,
      LLM.CooldownStore,
      LLM.RuntimeStatus,
      LLM.SkillsSidecarPolicy,
      Tooling.CommandProfile,
      WorkspaceGuard,
      SubAgentProgress,
      Orchestration.Blackboard,
      Orchestration.SubAgent,
      Orchestration.Scheduler,
      Graph.State,
      Graph.Nodes,
      Graph.Runner,
      Graph.Sync,
      Graph.Watcher,
      Heartbeat.GitHubWatcher,
      HookDispatcher
    ]
end
